#!/bin/bash

# This hook is called with the snake-cased name of the theme that has just been set.
# To put it into use, remove .sample from the name.

# Example: Show the name of the theme that was just set.
# notify-send "New theme" "Your new theme is $1"

# Sync tmux colors
"$HOME/.config/omarchy/hooks/tmux-theme-sync" "$1"
# Sync qutebrowser
instances=$(pgrep -x qutebrowser | wc -l)
if [ "$instances" -eq 1 ]; then
  #qutebrowser :config-source &
  qutebrowser :config-source
fi
