set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @plugin "jaclu/tmux-menus"
set -g @plugin "seebi/tmux-colors-solarized"
set -g @plugin "omerxx/tmux-sessionx"
set -g @plugin 'MackenzieStanger/tmux-popup'
set -g @plugin 'Peter-McKinney/tmux-open-file-nvim'
set -g @plugin 'AngryMorrocoy/tmux-neolazygit'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'alexwforsythe/tmux-which-key'
set -g @plugin 'ofirgall/tmux-window-name'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'
set -g @plugin 'laktak/extrakto'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plguin 'b0o/tmux-autoreload'
set -g @plugin 'sainnhe/tmux-fzf'

run '~/.config/tmux/plugins/tpm/tpm'

set -sg terminal-overrides ",*:RGB"
set -g escape-time 0
set -g renumber-windows on
set -g base-index 1
set -g pane-base-index 1
set -g pane-border-lines single
set -g status-position top

set-window-option -g mode-keys vi
bind-key -r h select-pane -L
bind-key -r j select-pane -D
bind-key -r k select-pane -U
bind-key -r l select-pane -R
bind -r - resize-pane -L 15
bind -r _ resize-pane -D 15
bind -r + resize-pane -U 15
bind -r = resize-pane -R 15
bind Space last-window

set-option -g @tmux-autoreload-entrypoints '~/.config/tux/theme-colors, ~/.config/tmux/tmux.conf'


# Source Omarchy theme colors (auto-synced on theme switch)
if-shell "[ -f ~/.config/tmux/theme-colors.conf ]" \
  "source-file ~/.config/tmux/theme-colors.conf"

# Enable OSC 52 clipboard forwarding for remote Neovim yanks.
set -as terminal-features ",*:clipboard"

bind-key S display-popup -E -w 100% -h 100% "sh -c '~/.config/tmux/session_selector.sh'"
set -g @continuum-restore 'on'
