windowrule {
    name = pygame-settings
    match:title = ^(pygame window)$
    float = on
    center = on
}

windowrule {
    name = steam-main-view
    match:class = ^(steam)$
    match:title = ^(Steam)$
    float = on
    center = on
    opacity = 1.0 override
    size = 1920 1080
}

windowrule {
    name = steam-friends-list
    match:class = ^(steam)$
    match:title = ^(Friends List)$
    size = 460 800
}

#windowrule {
#  name = mpv-pip
#  match:class = ^(mpv)$
#  match:fullscreen = false
#  float = on
#  pin = on
#  size = 30% 30%
#  move = 100%-w-20 100%-h-20
#}
